const destinations = [
  {
    name: 'Bodh Gaya',
    description:
      'Bodh Gaya is one of the most sacred Buddhist pilgrimage sites in the world. It is the place where Siddhartha Gautama attained enlightenment under the Bodhi Tree and became the Buddha. The Mahabodhi Temple, a UNESCO World Heritage Site, stands as an iconic symbol of this spiritual awakening.',
    location: 'Gaya district, Bihar',
    type: 'cultural',
    images: [
      '/destinations/bodh_gaya.png',
    ],
    coordinates: { lat: 24.6961, lng: 84.9912 },
    rating: 4.9,
    bestSeason: 'Winter',
    entryFee: 'Free (Temple: ₹100 for foreigners)',
    ecoScore: 85,
    interests: ['Spiritual', 'History', 'Architecture'],
    budget: 'Mid-range',
    activities: ['Meditation', 'Temple Visit', 'Photography'],
  },
  {
    name: 'Nalanda',
    description:
      'Nalanda was one of the greatest centers of learning in the ancient world. The ruins of this legendary Nalanda University draw scholars, historians, and travelers from around the globe. The site is a UNESCO World Heritage Site and houses an excellent museum displaying artifacts from excavations.',
    location: 'Nalanda district, Bihar',
    type: 'historical',
    images: [
      '/destinations/nalanda.png',
    ],
    coordinates: { lat: 25.1361, lng: 85.4436 },
    rating: 4.7,
    bestSeason: 'Winter',
    entryFee: '₹25 (Indians) / ₹300 (Foreigners)',
    ecoScore: 70,
    interests: ['History', 'Architecture'],
    budget: 'Budget',
    activities: ['Sightseeing', 'Museum Tour', 'History Walk'],
  },
  {
    name: 'Rajgir',
    description:
      'Rajgir is an ancient city surrounded by hills and valleys, renowned for its spiritual heritage connected to both Buddhism and Jainism. The Vishwa Shanti Stupa atop the Ratnagiri Hill, natural hot springs, and the ancient Cyclopean Wall make it a fascinating destination.',
    location: 'Nalanda district, Bihar',
    type: 'historical',
    images: [
      '/destinations/rajgir.png',
    ],
    coordinates: { lat: 25.0292, lng: 85.4218 },
    rating: 4.5,
    bestSeason: 'Winter',
    entryFee: 'Free',
    ecoScore: 80,
    interests: ['History', 'Nature', 'Spiritual'],
    budget: 'Mid-range',
    activities: ['Trekking', 'Cable Car Ride', 'Hot Spring Bath'],
  },
  {
    name: 'Valmiki National Park',
    description:
      'Valmiki National Park is the only national park in Bihar and part of the larger Valmiki Tiger Reserve. Located in the Himalayan foothills, it is home to Bengal tigers, leopards, gharials, elephants, and over 250 species of birds. The park offers unique wildlife safaris through diverse ecosystems.',
    location: 'West Champaran district, Bihar',
    type: 'eco',
    images: [
      '/destinations/valmiki.png',
    ],
    coordinates: { lat: 27.5411, lng: 84.3025 },
    rating: 4.6,
    bestSeason: 'Winter',
    entryFee: '₹200 (Indians) / ₹500 (Foreigners)',
    ecoScore: 95,
    interests: ['Wildlife', 'Nature', 'Photography'],
    budget: 'Luxury',
    activities: ['Safari', 'Bird Watching', 'Nature Walk'],
  },
  {
    name: 'Vikramshila',
    description:
      'Vikramshila was one of the most important centers of Buddhist learning during the Pala Empire. The ruins of this ancient university complex, along with a museum housing rare Buddhist manuscripts and sculptures, offer a remarkable glimpse into Bihar\'s glorious intellectual past.',
    location: 'Bhagalpur district, Bihar',
    type: 'historical',
    images: [
      '/destinations/vikramshila.png',
    ],
    coordinates: { lat: 25.3167, lng: 87.2833 },
    rating: 4.3,
    bestSeason: 'Winter',
    entryFee: '₹20 (Indians) / ₹200 (Foreigners)',
    ecoScore: 65,
    interests: ['History', 'Architecture'],
    budget: 'Budget',
    activities: ['Sightseeing', 'Museum Visit'],
  },
  {
    name: 'Pawapuri',
    description:
      'Pawapuri, also known as Apapuri (the sinless city), is an important Jain pilgrimage site where Lord Mahavira, the 24th Tirthankara, attained moksha (liberation). The Jal Mandir, a white marble temple situated in the middle of a lotus pond, is the most revered structure here.',
    location: 'Nalanda district, Bihar',
    type: 'cultural',
    images: [
      '/destinations/gaya.png',
    ],
    coordinates: { lat: 25.2214, lng: 85.5356 },
    rating: 4.4,
    bestSeason: 'Winter',
    entryFee: 'Free',
    ecoScore: 75,
    interests: ['Spiritual', 'Nature', 'Architecture'],
    budget: 'Mid-range',
    activities: ['Temple Visit', 'Photography'],
  },
  {
    name: 'Patna',
    description: 'The ancient city of Pataliputra, now Patna, stands majestically alongside the Ganges. As the capital of Bihar, it acts as the gateway to the state, merging deep historical roots extending back to the Magadha and Mauryan empires with modern urban bustle.',
    location: 'Patna district, Bihar',
    type: 'historical',
    images: ['/destinations/patna.png'],
    coordinates: { lat: 25.5941, lng: 85.1376 },
    rating: 4.5,
    bestSeason: 'Winter',
    entryFee: 'Free',
    ecoScore: 60,
    interests: ['History', 'Architecture'],
    budget: 'Mid-range',
    activities: ['City Tour', 'Museum Visit', 'River Boating'],
  },
  {
    name: 'Vaishali',
    description: 'Vaishali is famously known as the world\'s first republic and is immensely sacred to both Buddhists and Jains. It was here that Lord Buddha delivered his last sermon and where Lord Mahavira was born. The Ashokan Pillar stands proudly here.',
    location: 'Vaishali district, Bihar',
    type: 'cultural',
    images: ['/destinations/vaishali.png'],
    coordinates: { lat: 25.9875, lng: 85.1332 },
    rating: 4.6,
    bestSeason: 'Winter',
    entryFee: 'Free',
    ecoScore: 75,
    interests: ['History', 'Spiritual', 'Architecture'],
    budget: 'Budget',
    activities: ['Sightseeing', 'Meditation'],
  },
  {
    name: 'Rohtasgarh Fort',
    description: 'One of the most ancient and expansive hill forts in India, Rohtasgarh stands atop the Kaimur hills overlooking the Son River. Built by King Harishchandra, it displays formidable defensive architecture and breathtaking valley views.',
    location: 'Rohtas district, Bihar',
    type: 'historical',
    images: ['/destinations/rohtasgarh.png'],
    coordinates: { lat: 24.6293, lng: 83.9168 },
    rating: 4.4,
    bestSeason: 'Monsoon',
    entryFee: 'Free',
    ecoScore: 80,
    interests: ['Architecture', 'History', 'Nature'],
    budget: 'Budget',
    activities: ['Trekking', 'Photography', 'Exploration'],
  },
  {
    name: 'Kakolat Waterfall',
    description: 'Kakolat Waterfall is a naturally occurring cascade located deep within lush green forests. It is highly popular during the summer as a refreshing getaway, featuring a serene plunge pool steeped in mythological significance.',
    location: 'Nawada district, Bihar',
    type: 'eco',
    images: ['/destinations/kakolat.png'],
    coordinates: { lat: 24.7869, lng: 85.5786 },
    rating: 4.8,
    bestSeason: 'Summer',
    entryFee: 'Free',
    ecoScore: 90,
    interests: ['Nature', 'Photography'],
    budget: 'Budget',
    activities: ['Swimming', 'Picnic', 'Trekking'],
  },
  {
    name: 'Kesaria Stupa',
    description: 'Reaching a towering height, Kesaria Stupa is considered the tallest and largest Buddhist stupa in the world. Originally built by Emperor Ashoka, its majestic terraced structure attracts pilgrims and historians globally.',
    location: 'East Champaran district, Bihar',
    type: 'historical',
    images: ['/destinations/kesaria.png'],
    coordinates: { lat: 26.3400, lng: 84.8787 },
    rating: 4.6,
    bestSeason: 'Winter',
    entryFee: 'Free',
    ecoScore: 70,
    interests: ['Spiritual', 'History', 'Architecture'],
    budget: 'Budget',
    activities: ['Sightseeing', 'Photography'],
  },
  {
    name: 'Maner Sharif',
    description: 'Maner Sharif is a renowned Sufi shrine honoring the great Sufi Saint Makhdum Yahya Maneri. The architectural elegance of the tombs, particularly the Chhoti Dargah constructed with exquisite sandstones, is a marvel of Mughal design in Bihar.',
    location: 'Patna district, Bihar',
    type: 'cultural',
    images: ['/destinations/maner_sharif.png'],
    coordinates: { lat: 25.6481, lng: 84.8778 },
    rating: 4.5,
    bestSeason: 'Winter',
    entryFee: 'Free',
    ecoScore: 65,
    interests: ['Spiritual', 'Architecture', 'History'],
    budget: 'Budget',
    activities: ['Dargah Visit', 'Photography'],
  },
  {
    name: 'Barabar Caves',
    description: 'The Barabar Caves are the oldest surviving rock-cut caves in India, carved entirely out of massive granite ranges. Dating back to the Maurya Empire, they are renowned for their highly polished interior rock surfaces and fascinating acoustic properties.',
    location: 'Jehanabad district, Bihar',
    type: 'historical',
    images: ['/destinations/barabar.png'],
    coordinates: { lat: 25.0069, lng: 85.0620 },
    rating: 4.7,
    bestSeason: 'Winter',
    entryFee: 'Free',
    ecoScore: 85,
    interests: ['History', 'Architecture', 'Nature'],
    budget: 'Budget',
    activities: ['Caving', 'Trekking', 'Sightseeing'],
  },
  {
    name: 'Sanjay Gandhi Jaivik Udyan',
    description: 'Popularly known as the Patna Zoo, this vast zoological and botanical garden is a major hub of eco-tourism in the capital. It houses dense vegetation, an extensive aquarium, and a rich array of mammals, reptiles, and birds.',
    location: 'Patna district, Bihar',
    type: 'eco',
    images: ['/destinations/sanjay_gandhi.png'],
    coordinates: { lat: 25.5996, lng: 85.0975 },
    rating: 4.6,
    bestSeason: 'Winter',
    entryFee: '₹30',
    ecoScore: 90,
    interests: ['Nature', 'Photography'],
    budget: 'Budget',
    activities: ['Safari', 'Boating', 'Picnic'],
  },
  {
    name: 'Takht Sri Patna Sahib',
    description: 'A magnificent Gurdwara built natively commemorating the birthplace of Guru Gobind Singh, the tenth Guru of the Sikhs. The stunning white architecture rests peacefully on the banks of the mighty Ganges.',
    location: 'Patna district, Bihar',
    type: 'cultural',
    images: ['/destinations/patna_sahib.png'],
    coordinates: { lat: 25.5891, lng: 85.2341 },
    rating: 4.9,
    bestSeason: 'Winter',
    entryFee: 'Free',
    ecoScore: 80,
    interests: ['Spiritual', 'History'],
    budget: 'Budget',
    activities: ['Prayer', 'Langar', 'Sightseeing'],
  }
];

const festivals = [
  {
    name: 'Chhath Puja',
    location: 'Statewide (Major ghats: Patna, Gaya)',
    month: 'October/November',
    description:
      'Chhath Puja is the most celebrated folk festival of Bihar, dedicated to the Sun God (Surya) and Chhathi Maiya. Celebrated over four days, devotees offer prayers at riverbanks during sunrise and sunset. It is one of the most environmentally friendly festivals, with no use of idols or synthetic colors.',
    images: [
      '/destinations/patna.png',
    ],
  },
  {
    name: 'Sonepur Mela',
    location: 'Sonepur, Saran district',
    month: 'November',
    description:
      'Sonepur Mela, held at the confluence of the Ganga and Gandak rivers, is one of the largest livestock and trade fairs in Asia. Traditionally held after Kartik Purnima, it runs for about a month and attracts traders, artisans, performers, and tourists from across India and the world.',
    images: [
      '/destinations/vaishali.png',
    ],
  },
  {
    name: 'Rajgir Mahotsav',
    location: 'Rajgir, Nalanda district',
    month: 'October',
    description:
      'Rajgir Mahotsav is a cultural extravaganza organized by the Bihar government to showcase the art, music, dance, and cultural heritage of Bihar. Held amid the ancient hills of Rajgir, the three-day festival features folk performances, classical music, and artisan markets.',
    images: [
      '/destinations/rajgir.png',
    ],
  },
  {
    name: 'Buddha Purnima',
    location: 'Bodh Gaya, Gaya district',
    month: 'May',
    description:
      'Buddha Purnima marks the birth, enlightenment, and death of Gautama Buddha and is celebrated with great devotion in Bodh Gaya. Thousands of Buddhist pilgrims from Tibet, Japan, Sri Lanka, Thailand, and around the world visit the Mahabodhi Temple to offer prayers and meditate.',
    images: [
      '/destinations/bodh_gaya.png',
    ],
  },
];

const ecoSites = [
  {
    name: 'Valmiki Tiger Reserve',
    wildlife: [
      'Bengal Tiger',
      'Leopard',
      'Asian Elephant',
      'Gharial',
      'Sloth Bear',
      'Wild Boar',
      'Spotted Deer',
      'Indian Bison',
    ],
    ecoActivities: [
      'Jeep Safari',
      'Elephant Safari',
      'Bird Watching',
      'Nature Walks',
      'River Rafting on Gandak',
      'Wildlife Photography',
    ],
    parkType: 'Tiger Reserve & National Park',
    location: 'West Champaran district, Bihar',
    images: [
      '/destinations/valmiki.png',
    ],
  },
  {
    name: 'Kawar Lake Bird Sanctuary',
    wildlife: [
      'Siberian Crane',
      'Bar-headed Goose',
      'Northern Pintail',
      'Common Pochard',
      'Gadwall',
      'Eurasian Wigeon',
      'Indian Spot-billed Duck',
    ],
    ecoActivities: [
      'Bird Watching',
      'Boat Rides',
      'Nature Photography',
      'Wetland Ecology Tours',
    ],
    parkType: 'Bird Sanctuary & Ramsar Wetland',
    location: 'Begusarai district, Bihar',
    images: [
      '/destinations/kakolat.png',
    ],
  },
  {
    name: 'Bhimbandh Wildlife Sanctuary',
    wildlife: [
      'Leopard',
      'Nilgai',
      'Wild Boar',
      'Indian Python',
      'Porcupine',
      'Sambar Deer',
      'Jackal',
    ],
    ecoActivities: [
      'Nature Trekking',
      'Hot Spring Bathing',
      'Wildlife Safari',
      'Bird Watching',
      'Rock Climbing',
    ],
    parkType: 'Wildlife Sanctuary',
    location: 'Munger district, Bihar',
    images: [
      '/destinations/bhimbandh.png',
    ],
  },
];

module.exports = { destinations, festivals, ecoSites };
